name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17", "1.18", "1.19", "1.20", "1.21", "1.22", "1.23"]
    steps:
      - uses: actions/checkout@v3

      - name: setup go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: build
        run: go build -v ./...

      - name: test
        run: go test -coverprofile=coverage.txt -v ./...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
